FROM debian:bookworm-slim

RUN apt clean && apt update && apt upgrade -y

# 検証用ツール
RUN apt install -y vim \
        # ping command
        iputils-ping \
        # ip command
        iproute2 \
        # traceroute command
        traceroute \
        # wiresharkのコマンドライン版
        tshark \
        # 改行文字の変換
        dos2unix

COPY ./init.sh /home/
RUN chmod +x /home/init.sh && dos2unix /home/init.sh

CMD ["/home/init.sh"]